apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h73q4ltba-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-dd56013b07.n2dw.p3.openshiftapps.com/rhtap/rhtap-qe:ab29e99930f180fa969e98ed58619030194779c3@sha256:140b846eb70676de84cbd9bab7ac3d3f252fc88c46505fc651639756d76d4080
          name: container-image
